config/routes.rb
Rails.application.routes.draw do
  get 'tailwind/index'
  root 'tailwind#index'
  get  '/about' , to: 'pages#about'
  get  '/contact' , to: 'pages#contact'


  get  '/resumes' , to: 'resumes#index'
  get  '/resumes/new' , to: 'resumes#new'
  post '/resumes' , to: 'resumes#create'
  get  '/resumes/:id' , to: 'resumes#show', as: 'resume'
  get  '/resumes/:id/eidt' , to: 'resumes#eidt', as: 'eidt_resume'
  patch '/resumes/:id', to: 'resumes#update'
  delete '/resumes/:id', to: 'resumes#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
    validates :name, :tel, presence: true
    validates :email, presence: true, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/}


    def self.search(keyword)
        where("intro like ?", "%#{keyword}%")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    private
    def record_not_found
      render file: Rails.root.join('public', '404.html'),
             layout: false,
             status: 404 and return
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end

    def contact
    end

    def home
         
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :find_resume, only: [:show, :eidt, :update, :destroy]
    def index
      @resumes = Resume.order(created_at: :desc)

      if params[:keyword].present?
        @resumes = @resumes.search(params[:keyword])
      end
    end
    def new
        @resume = Resume.new
    end

    def create
      @resume = Resume.new(resume_params)
      
      if @resume.save
        redirect_to resumes_path, notice: '新增履歷成功'
      else
        render :new
      end
    end
    def show

    end

    def eidt

    end
    def update

      if @resume.update(resume_params)
        redirect_to resumes_path, notice: "修改成功"
        else
          render :eidt
      end
    end

    def destroy
      @resume.destroy
      redirect_to resumes_path, notice: "刪除成功"
    end

    private
  def resume_params
    params.require(:resume).permit(:name, :email, :tel, :skill, :intro, :city, :education, :experience, :portfolio)
  end
  def find_resume
    @resume = Resume.find(params[:id])
  end
end

app/controllers/tailwind_controller.rb
class TailwindController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_date(date)
        date.strftime('%Y/%-m/%-d')
      end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/peng_helper.rb
module PengHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/tailwind_helper.rb
module TailwindHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobbank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' if flash.any? %>
    <%= render 'shared/navbar' %>

  <main>
    <%= yield %>
  </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於
    
</h1>

app/views/pages/contact.html.erb
<h1>聯繫</h1>

app/views/pages/home.html.erb
<h1>首頁</h1>

app/views/resumes/_form.html.erb
<%= form_for(resume) do |f| %>
  <%= render 'shared/form/error_message', record: resume %>

  <div class="field">
    <%= f.label :name, '姓名' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :tel, '電話' %>
    <%= f.telephone_field :tel %>
  </div>

  <div class="field">
    <%= f.label :skill, '技能' %>
    <%= f.text_field :skill %>
  </div>

  <div class="field">
    <%= f.label :intro, '簡介' %>
    <%= f.text_area :intro %>
  </div>

  <div class="field">
    <%= f.label :city, '居住地' %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :education, '學歷' %>
    <%= f.text_area :education %>
  </div>

  <div class="field">
    <%= f.label :experience, '經歷' %>
    <%= f.text_area :experience %>
  </div>

  <div class="field">
    <%= f.label :portfolio, '作品集' %>
    <%= f.text_area :portfolio %>
  </div>

  <hr>
  <%= f.submit %>
<% end %>

app/views/resumes/_resume.html.erb
<section class="resume-card">
  <header>
    <div class="cover">
    <%= link_to resume_path(resume) do %>
      <img src="https://fakeimg.pl/350x200/ff0000,128/000,255">
    <% end %>
    </div>
  </header>

  <section class="info">
    <div class="basic-info">
    <h2 class="username"><%= resume.name %></h2>
    <address class="location"><%= resume.city %></address>
    </div>
    <article class="intro truncate">
    <%= link_to resume.intro&.truncate(75), resume_path(resume) %>
    </article>
  </section>

  <footer>
  <time class="update-time"><%= format_date(resume.updated_at) %></time>
  <div class="functions">
    <%= link_to '編輯', eidt_resume_path(resume), class: 'btn' %>
    <%= link_to '建立副本', '#', class: 'btn' %>
    <%= link_to '刪除', resume_path(resume), class: 'btn btn-danger',
                        method:'delete',
                        data: {confirm: '確認刪除?'} %>
  </div>
  </footer>

</section>

app/views/resumes/eidt.html.erb
<h1>編輯履歷</h1>

<%= render 'form', resume: @resume %>

app/views/resumes/index.html.erb
<h1>履歷列表</h1>

<form action="">
  <input type="text" name="keyword" value="<%= params[:keyword] %>" placeholder="輸入關鍵字">
  <input type="submit" value="查詢">

</form>
<%= link_to '新增履歷', resumes_new_path %>

<div class="resume-container">
  <% @resumes.each do |resume| %>
    <%= render 'resume', resume: %>
  <% end %>
</div>

app/views/resumes/new.html.erb
<h1>新增履歷</h1>

<%= form_for(@resume) do |f| %>

    <%= render 'shared/form/error_message', record: @resume %>
    <div class="field">
    <%= f.label :name, '姓名' %>
    <%= f.text_field :name %>
    </div>

    <div class="field">
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :tel, '電話' %>
    <%= f.telephone_field :tel %>
  </div>

  <div class="field">
    <%= f.label :skill, '技能' %>
    <%= f.text_field :skill %>
  </div>

  <div class="field">
    <%= f.label :intro, '簡介' %>
    <%= f.text_area :intro %>
  </div>

  <div class="field">
    <%= f.label :city, '居住地' %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :education, '學歷' %>
    <%= f.text_area :education %>
  </div>

  <div class="field">
    <%= f.label :experience, '經歷' %>
    <%= f.text_area :experience %>
  </div>

  <div class="field">
    <%= f.label :portfolio, '作品集' %>
    <%= f.text_area :portfolio %>
  </div>

<%= f.submit%>
<%end%>

app/views/resumes/show.html.erb
<h1><%= @resume.name %> 履歷</h1>

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |t| %>
  <% if flash[t] %>
      <div class="flash flash-<%= t %>">
        <%= flash[t] %>
      <button>X</button>
      </div>
  <% end %>   
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
      
<%= link_to'首頁', root_path %></a>

      <ul>
      <li><%= link_to'履歷', resumes_path %></a></li>
        <li><%= link_to'關於我們', about_path %></a></li>
        <li><%= link_to'聯絡我們', contact_path %></a></li>

      </ul>
    </nav>

app/views/shared/form/_error_message.html.erb
<% if record.errors.any? %>
    <section class="error-message">
      <ul>
      <% record.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>  
      </ul>
      </section>
    <% end %>    

app/views/tailwind/index.html.erb
<h1 class="m-8 text-6xl text-red-900">Tailwind#index</h1>
<p class="font-bold text-green-800 m-10">Find me in app/views/tailwind/index.html.erb</p>